### ISSUE TITLE
Back button remapping

### ISSUE THREAD

**Issue by t0rzz** [crdroidandroid/crdroid_features#1]
Hey guys, this is not an issue, but a feature request. I see no back button remapping settings in CrDroid latest ver. It would be nice to have a long-press kill foreground app action for that button.

Also, as seen in many custom ROMs (non-AOSP), would it be possible to make a switch for whether one can unlock Android with fingerprint right after a reboot or not instead of being forced to insert the passcode?

Thank you.

Using S9 exynos. Your kernel, latest build.

Thank you guys, great job.

**Comment by gwolf2u** [comment]
@neobuddy89 current code supports this old Nougat feature?

**Comment by neobuddy89** [comment]
Yes. Long press back button mapping feature has been added.
