### ISSUE TITLE
OnePlus 11 CHP2451 (NA variant) fast charge greyed out

### ISSUE THREAD

**Issue by GreatKingCody** [crdroidandroid/crdroid_features#100]
Having an issue under the OnePlus settings where `Fast charge` is greyed out and toggled off. I vaguely remember seeing that I could select the option when I first flashed the ROM but when I went to check it yesterday I couldn't toggle it. Is there a setting that would be making it unavailable? My phone wasn't charging when I looked at it, for what its worth.

**Comment by gwolf2u** [comment]
wrong place to report this
