### ISSUE TITLE
App lock in CrDroid 9.10

### ISSUE THREAD

**Issue by frankh93** [crdroidandroid/crdroid_features#101]
I just updated to latest version and there isn't app lock under settings/privacy and security, where it was all the time... Is it bug or removed?
Thanks in advance

**Comment by neobuddy89** [comment]
You can access these settings from crdroid home alternatively.

**Comment by frankh93** [comment]
> You can access these settings from crdroid home alternatively.

I was able to select what apps to lock but the feature to redact notifications wasnt there. Thats why I was asking

**Comment by neobuddy89** [comment]
WIll look more into this. Which gapps are you using?

**Comment by frankh93** [comment]
> WIll look more into this. Which gapps are you using?

I used nikgapps (omni variant). When I said I wasnt able to get to the other options I meant when I checked through launcher options... In that I can only set it locked and hide it from launcher
