### ISSUE TITLE
Poco F2 Pro Face Unlock

### ISSUE THREAD

**Issue by rmvn** [crdroidandroid/crdroid_features#107]
Hello.

Using crdroid 10.1 on Poco F2 Pro.

The front facing camera is a pop up camera on this phone.

Soo if I'm with face unlock active, every time I turn the screen on the camera pops up trying to unlock the phone, some times this very useful, some times very inconvenient.

Would it be possible to implement a swipe up gesture on lock screen, to use face unlock only when we want it? 

That way camera wouldn't be always popping up.

Thank you.

**Comment by gwolf2u** [comment]
our current implementation doesn't support that
will see maybe in the future
