### ISSUE TITLE
Restore Native Superuser Option on crDroid 5.x

### ISSUE THREAD

**Issue by moriel5** [crdroidandroid/crdroid_features#16]
Magisk is a very good solution, however not everyone needs it.

When trying to add the LOS addonsu package on the LG G3 (D855), I have discovered that crDroid 5.0 deletes the su binary upon boot.
Additionally, the superuser activity is nowhere to be found within the ROM (verified with Nova Launcher).

**Comment by gwolf2u** [comment]
tried seeking in dev options for su?

**Comment by moriel5** [comment]
Sorry, the ROM has been updated since then.
Now it is there, it's just not working (just getting permission denied), despite me having enabled root for both ADB and devices.

And why was my SeLinux thread limited? How exactly is enabling SeLinux a security issue? It is disabled by default.

**Comment by gwolf2u** [comment]
devs should focus on building with SeLinux enabled 
if it's disabled it lowers security (seek over Google what SeLinux does)

as for root, maybe app is not build to read built-in root

**Comment by moriel5** [comment]
Nay, it is the built in terminal.
And I'm sorry about my rudeness, I had sincerely thought my issues were caused was by design choices, it is probably due to version 5.x being so new, and the dev still working on these.

Please do not lock this thread, just so that I'll be able to post when these issues are resolved, so that others will not make the same mistake as I have.

**Comment by neobuddy89** [comment]
@moriel5 how are you adding it when you say "When trying to add the LOS addonsu package "

**Comment by moriel5** [comment]
SeLinux Update: I had flashed crDroid 4.7, and SeLinux was also set to permissive by default there.
Perhaps the developer has had issues with stabilization with SeLinux set to enforcing?

**Comment by gwolf2u** [comment]
reason to ask device maintainer for help
