### ISSUE TITLE
Add Option to Modify SeLinux State to crDroid 5.x

### ISSUE THREAD

**Issue by moriel5** [crdroidandroid/crdroid_features#17]
I would like to enable SeLinux on crDroid, as well as to be able to set whether it is strict or permissive.

Can a toggle be added to select between these 3 options? It is fine if it requires a reboot.

**Comment by gwolf2u** [comment]
this won't be added 
too much of a hassle and lowers security 
if you want to run permissive, there is a zip (won't link here) to flash in TWRP and changes kernel to that
