### ISSUE TITLE
Hidding quick settings on locked screen

### ISSUE THREAD

**Issue by DevNaNuvem** [crdroidandroid/crdroid_features#18]
Hello guys, first thank you for this gorgeous Android.

I have a suggestion for you, just like we can disable the shutdown/restart funtion on lockscreen (A great security feature). It would be really awesome to have the option to disable also the quick settings on locked screen.

In case you have your device stolen, the thief would not be able to turn connections off (unless with your password). Making your device trackable if you have a tracking app.

**Comment by DouglasGomes123** [comment]
I agree, it would be great

**Comment by gwolf2u** [comment]
commits?

**Comment by gwolf2u** [comment]
feature is now implemented 
https://github.com/crdroidandroid/android_frameworks_base/commit/f3852513d886c5e7ead55b5cf8e8647584c3c3d5
