### ISSUE TITLE
Recents button remapping

### ISSUE THREAD

**Issue by silv7k** [crdroidandroid/crdroid_features#2]
Guys, can you please add Recents hardware button remapping to the settings?
We don't have it in the latest official build for our Zuk Z1.

**Comment by gwolf2u** [comment]
@silv7k is any custom Oreo based ROM supporting this as of now?

**Comment by silv7k** [comment]
They sure do. In fact crDroid is the first Oreo ROM I've tried on my Zuk that doesn't support Recents button.
SCREW'D AOSP is an example:
https://forum.xda-developers.com/zuk-z1/orig-development/rom-screw-d-aosp-4-1-zuk-z1-t3750161

**Comment by gwolf2u** [comment]
I feel stupid now 
the feature is already implemented 
see DUI Smartbar under crDroid Settings -> Navigation

**Comment by silv7k** [comment]
Well, that's not what I meant. I mean hardware button customization, as we have now in crDroid Settings → Buttons. There's a number of buttons to customize (remap), but no Recents.
![screenshot_settings_20180622-023956](https://user-images.githubusercontent.com/32778144/42279776-6b141dca-7f8e-11e8-81c3-882c39676660.png)
That's what we need (screenshot from MM ROM):
![screenshot_20180704-162252](https://user-images.githubusercontent.com/32778144/42279831-8d8d9476-7f8e-11e8-977c-587a9b9746e5.png)

**Comment by neobuddy89** [comment]
This is already present.
Using OP5. Please check with maintainer if not present.

**Comment by silv7k** [comment]
@neobuddy89 thanks for the info.
Will clean flash the next update, then will contact our maintainer.
