### ISSUE TITLE
Improve Android 10 gestures

### ISSUE THREAD

**Issue by Madis0** [crdroidandroid/crdroid_features#21]
Google implemented a new style of gestures in Android 10. 

While it is a major improvement over Android 9 ones, it still could use a few improvements, perhaps CrDroid could implement those as an option.

- Disable back action on left edge (to keep drawer menu slide working as before) 
- Hide the home bar (to save screen space, home action should still work the same)
- Enable gestures with any launcher (planned to do by Google anyway, so this is less important)

**Comment by gwolf2u** [comment]
stuff is getting added to crDroid 6 step by step
please be patient for more features
