### ISSUE TITLE
[Feature request] Long screenshot

### ISSUE THREAD

**Issue by shvchk** [crdroidandroid/crdroid_features#22]
It would be nice to have an integrated ability to create longshot (long screenshot). Recently Pixel Experience integrated it: https://github.com/PixelExperience/packages_apps_Longshot using https://github.com/jhenrique09/OPLongshot as a base.

And thanks for this awesome ROM :metal: 

UPD: Well, looking at those repos more closely, it isn't an original code, but rather unpacked third-party (OnePlus?) code. Also, not sure about its license.

Maybe there are other open source implementations?

**Comment by gwolf2u** [comment]
stuff is getting added step by step in crDroid 6
so please be patient
