### ISSUE TITLE
Tap to Sleep option

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#24]
The Tap to Sleep option under Display section in settings doesn't affect the individual one for lock screen under crDroid Settings section and vice versa.

Toggling the one in Display section (which should affect both, according to description) toggles on/off the status bar one and toggling the individual one affects the one under Display. This is not the case for the lock screen option.

**Comment by gwolf2u** [comment]
the one in settings is based on doze app from device tree
ask device maintainer to remove it

**Comment by AndyL964** [comment]
@neobuddy89, I apologize if I've been a bit naggy about this, but this issue is still somewhat relevant.

When disabling the one in Display section, it does also disable the individual ones but instead reverts them to their previous state.

**Comment by neobuddy89** [comment]
cannot comprehend what's the issue here.
one under settings > display is for statusbar - works fine
one under crdroid settings is for lockscreen - works fine

**Comment by AndyL964** [comment]
> 
> 
> cannot comprehend what's the issue here.
> one under settings > display is for statusbar - works fine
> one under crdroid settings is for lockscreen - works fine

Description for the one under Display: "Double-tap on the status bar OR lockscreen to turn off the display", so doesn't that imply it affects both?

https://streamable.com/os66jz

**Comment by neobuddy89** [comment]
Removed one under Settings > Display.
Use either from crdroid > status bar or crdroid > lockscreen.

https://github.com/crdroidandroid/android_packages_apps_Settings/commit/6e7c034fcafd2664d82b40c8ebe0c6c856e7a34e
