### ISSUE TITLE
Pulse if battery low

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#26]
On first boot of ROM, the LED flashes when on low battery, even though the battery light options are disabled by default under crDroid Settings > Notifications > Battery.

If the option is toggled, settings become consistent as normal.

**Comment by neobuddy89** [comment]
Fixed.
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/9dc256da6db61be2530c1770d46f2cd5600fa0c7
