### ISSUE TITLE
Ambient display disables tap to wake

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#27]
The sensor options under crDroid Settings > Ambient Display (eg. hand wave) when triggered allows sliding on the screen to unlock the phone.

Once triggered, however, tap to wake doesn't work anymore even after you can no longer slide on the screen (after 5 seconds has passed).

**Comment by neobuddy89** [comment]
Works fine on my latest build - it has doze fixes - might be helpful.

**Comment by AndyL964** [comment]
I've just tested on the latest build I've had installed and both double tapping and sliding up stays active indefinitely!

**Comment by neobuddy89** [comment]
I meant my personal build. Not released one.
Did you build from sources?

**Comment by AndyL964** [comment]
No, I'm using the release build. Used the updater in Settings to install.
