### ISSUE TITLE
Malfunctioning touchscreen gesture actions

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#29]
There are two touchscreen gesture actions that do not work as expected:
Camera - this one doesn't do anything at all
Messages - this one opens the wrong app (Google Photos) rather than the default messaging app I've set

**Comment by neobuddy89** [comment]
Fixed.

**Comment by AndyL964** [comment]
Discovered some more on the latest build.
Right triggers left.
Down is right
Left is down

**Comment by gwolf2u** [comment]
> Discovered some more (for one finger swipes) on the latest build:
> 
>     * Right triggers left
> 
>     * Down triggers right
> 
>     * Left triggers down

That's device specific issue
