### ISSUE TITLE
Ambient Display settings issues

### ISSUE THREAD

**Issue by Nerva72** [crdroidandroid/crdroid_features#3]
Go to Settings > crDroid Settings > User Interface > Ambient Display, and there are several options, including "Battery info" with the description "Display current battery info while dozing." Below it is another option, "Always on", with the description, "Show time, notification icons, and other info. Increased battery usage." What's odd is that even though the battery info option depends on the always on being enabled (the display obviously needs to be on in order to show the battery), disabling "Always on" does not cause "Battery info" to gray-out, per Android settings conventions.

In general, the Ambient Display options seem to need some work, particularly in comparison to the rest of the crDroid settings, which are quite good. For starters, the fact the settings menu called "Ambient display" has a sub-menu also called "Ambient display", is a warning sign that the names for things in that section haven't been completely thought-through. What's also worrisome is the first (higher level) "Ambient display" settings screen has options for "Pick up" (pulse notification on pick up), "Hand wave" (pulse notifications on hand wave), and "Pocket" (pulse notifications on removal from pocket), but then if you go to the second (deeper) "Ambient display" settings screen, it ALSO has options called "Hand wave" (pulse notifications on hand wave), "Pocket" (pulse notifications on removal from pocket), and "Proximity wake" (wake device on hand wave). So it's as if the deeper settings screen is a different revision of the higher-level settings screen that got left in place when the settings were revised. It needs to be cleaned up.

**Comment by hondajohn88** [comment]
I disagree regarding the battery charge display in ambient settings. The screen doesn't need to be always on for that setting to be useful. If you want to check battery charge if ambient screen is not set to always on, you can either tip the phone, pick up the phone, hand wave, double tap to wake, or see it if you have notifications wake your phone

Regarding the multiple ambient display settings screens, which phone are you using? There are a lot of phone models this rom is made for, and judging by the ambient menu (only one ambient display menu) on my phone (mix 2), what you're seeing may be limited to one, or a small number of models.

**Comment by hondajohn88** [comment]
Ahh, OK, I misunderstood about the battery info. My apologies for that.

**Comment by Nerva72** [comment]
As I said, I have a Verizon Galaxy S5 (klte).

**Comment by gwolf2u** [comment]
rejected
ask your maintainer to implement proper modifications 
if he does not know, ask over crDroid Telegram
