### ISSUE TITLE
Image preview for custom QS header

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#31]
Add a small editor to make it easier to select which part of the image you want to be included in the header. This way, you won't have to crop the image beforehand.

**Comment by gwolf2u** [comment]
will get added if possible

**Comment by AndyL964** [comment]
Why not add some tags and leave this open until perhaps implemented in the future rather than close it?

**Comment by AndyL964** [comment]
> 
> 
> will get added if possible

I'm curious as to why you would rather close it instead of adding some descriptive tags and leaving it open.
