### ISSUE TITLE
Font color of "Copy to clipboard"

### ISSUE THREAD

**Issue by maniusq** [crdroidandroid/crdroid_features#33]
Hi guys,
because of the font color of "Copy to clipboard" (German: "In die Zwischenablage kopieren") the text is not readable in the contacts app.

I have attached a screenshot.
<img src="https://user-images.githubusercontent.com/59109219/80303610-952df680-87b1-11ea-8c6c-1878cd8897a8.jpg" width="100px">

**Comment by neobuddy89** [comment]
Fixed by @Hikari-no-Tenshi 
https://github.com/crdroidandroid/android_packages_apps_Contacts/commit/aa6ddfd5ce46b42160ea0186a4fa07db3034bdcc
