### ISSUE TITLE
Unable to use airpods

### ISSUE THREAD

**Issue by Th0rgal** [crdroidandroid/crdroid_features#34]
Hello,

I just installed crdroid 6.5 on my Redmi note 7. The phone is rooted (with Magisk) and everything works ...except my airpods (model 2). In fact I was able to pair them with the phone and even to connect them (it show they are connected and audio is enabled). It was working with stock MIUI 11 (android 9 and 10). But when I start the music, the sound comes from my phone and not from my airpods. Did I do something wrong? Is there a fix? I listen to music everyday with my airpods so I really need their support. 

Thank you very much,
Thomas

**Comment by FloppyCheese** [comment]
I am having the same issue with all Bluetooth audio devices. Let me know if you need any more information.

**Comment by gwolf2u** [comment]
audio config might be wrong or maybe unsupported bt codec
however am not sure if this is common across devices so try to logcat and maybe send to device specific forum for now
closing this for now until more feedback is available
