### ISSUE TITLE
Adaptive playback feature doesn't work correctly with bluetooth headsets

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#36]
Unlike when using speaker, you have to decrease the volume once or twice after no sound can be heard for media playback to be automatically paused.

**Comment by neobuddy89** [comment]
@spacetree1 can you please check?

**Comment by spacetree1** [comment]
> @spacetree1 can you please check?

i will check in the morning.

**Comment by spacetree1** [comment]
Tested right now. No issues were detected. 
Linked a screenrecord
https://youtu.be/vTYJqRw5Vrg

**Comment by AndyL964** [comment]
I'm using a Riff Wireless. For some reason, sound stops a few steps above minimum in the volume panel, even though I can clearly still hear the music until it reaches minimum in a screen recording.

It's probably an issue specific to my device.
