### ISSUE TITLE
Make date optional for lock screen/always on display

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#37]
To allow for even more customization, make showing the date on the optional.

When the date is not shown, Pixel style option for lock screen weather section should be greyed out to avoid confusion.

**Comment by neobuddy89** [comment]
Screen weather will roll back to non-pixel style when date is not shown.
https://github.com/crdroidandroid/android_frameworks_base/commit/88b339567694bbea1f3c38242a08d5f60777b76c

Making date optional is feature request we may/may not add.

**Comment by AndyL964** [comment]
> Screen weather will roll back to non-pixel style when date is not shown.
> [crdroidandroid/android_frameworks_base@88b3395](https://github.com/crdroidandroid/android_frameworks_base/commit/88b339567694bbea1f3c38242a08d5f60777b76c)
> 
> Making date optional is feature request we may/may not add.
Can't seem to get this option to disappear after switching to Type clock style.

Also, does it affect the new center Type style as well?
