### ISSUE TITLE
"Type" clock style doesn't show always on display music ticker or weather

### ISSUE THREAD

**Issue by AndyL964** [crdroidandroid/crdroid_features#40]
When switching to this clock style, this issue persists for all other styles as well until you switch back to the default non-bolded clock style.

**Comment by neobuddy89** [comment]
TypeClock disables date view. This is as per AOSP design.
Switching back to custom clock - date view will be visible. Fixed:
https://github.com/crdroidandroid/android_frameworks_base/commit/a96f6c9e16d6d593501979f9235fcb66b02fd2d1

TypeClock with date is feature request - we may/may not add.
