### ISSUE TITLE
Using fingerprint to unlock apps like bank apps or passwordmanagers

### ISSUE THREAD

**Issue by Offerel** [crdroidandroid/crdroid_features#44]
Hi there. It seems that using fingerprint to unlock apps like banking apps or password manager apps does not work. Im not a Android developer, so i don't have the right skill to analyze the problem. But if i understand it correctly, this seems to be a problem with the implementation of the keystore or at least how keystore works in custom ROM's. Maybe you can help to make using fingerprint work with such apps?

**Comment by gwolf2u** [comment]
working good here
