### ISSUE TITLE
Manual network search 

### ISSUE THREAD

**Issue by bibiii-79** [crdroidandroid/crdroid_features#50]
Hello Guys, in instantnoodlep I still have issue with:
- manual network search ( I am crossing the border often, and this function not working), the modem is is not responding , giving an error.... Shortly this function is not working... Otherwise the rom is pretty stable ....for daily use.
- the screen refresh rate cannot be switched to 90hz, And 1080p. Is only 120hz on or off.
-

**Comment by gwolf2u** [comment]
please report device specific issues in forums or telegram
github is for code related issues
