### ISSUE TITLE
[Feature request] GrapheneOS's Sandboxed Play services

### ISSUE THREAD

**Issue by dimqua** [crdroidandroid/crdroid_features#56]
I think it'd be useful to integrate GrapheneOS's patches that basically allow to run google play services as unprivileged apps. LOS devs refused to integrate them, but they were already ported by someone else, more info here: https://forum.xda-developers.com/t/guide-grapheneoss-sandboxed-play-services-in-your-rom.4340557/

I know that crDroid already supports microG, but unfortunately these are some apps that don't work with it correctly. These patches provide a compromise solution allowing users to use such apps under the separate work profile or user account without the need of installing GPlay services system-wide.

**Comment by gwolf2u** [comment]
do submit PR if you want to add anything to source
