### ISSUE TITLE
[Feature request] Porting the existing functionality of LineageOS, Moto Gestures.

### ISSUE THREAD

**Issue by daiaji** [crdroidandroid/crdroid_features#57]
![Screenshot_20220225-225439_Trebuchet](https://user-images.githubusercontent.com/25875791/155737078-643eb7f7-5b89-4171-9f12-297a69e8494e.png)
I've used this feature on Moto Z2 Force (nash), but it doesn't seem to be enabled on Xiaomi Redmi K40 (alioth), I don't know why. This feature works great and should be enabled on all devices.

**Comment by gwolf2u** [comment]
device specific 
ask maintainer in forum
