### ISSUE TITLE
[Feature request] The status bar clock seems to lack LineageOS-style auto-hide.

### ISSUE THREAD

**Issue by daiaji** [crdroidandroid/crdroid_features#59]
Since there is usually a clock on the launcher, the status bar clock is really useless, the LineageOS-style auto-hiding status bar clock is really helpful.
![Screenshot_20220228-203733_Trebuchet](https://user-images.githubusercontent.com/25875791/155987464-6b9e74b9-e140-40c0-88d8-edf3c717fefb.png)

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/ab433187e9868b399136b6d092a6626000ba1405
