### ISSUE TITLE
[Feature request] Added screenshot interaction.

### ISSUE THREAD

**Issue by daiaji** [crdroidandroid/crdroid_features#60]
https://user-images.githubusercontent.com/25875791/156194208-daaa26eb-7a79-40a2-a9db-15b6d5dc3f20.mp4

https://user-images.githubusercontent.com/25875791/156194377-1efcb7d4-99b9-469b-b01a-ccb290651704.mp4

As you can see, the screenshot button has almost no interaction, I didn't even know I finished the screenshot, but the screenshot button here should have full interaction.

Also, I think the color setting of the tap prompt should be increased. As you can see, in the first video, I pressed the screenshot button, but since there is no feedback and the color of the tap prompt is very light, the tap prompt is almost invisible. visible.

**Comment by gwolf2u** [comment]
this is for crDroid 7
crDroid 8 already has better screenshot management
