### ISSUE TITLE
[Feature request]Porting Resurrection Remix OS for automatic brightness can set the minimum brightness function.

### ISSUE THREAD

**Issue by daiaji** [crdroidandroid/crdroid_features#61]
![Screenshot_20220301-232224525](https://user-images.githubusercontent.com/25875791/156196834-d79d5d4b-a95f-4fba-9f21-45e8e81315fc.jpg)
Even with Android 11, Android's auto-brightness still doesn't work very well, often making the screen unacceptably low in low ambient light.
Making the minimum brightness settable is a crude solution, but it works.
At least when I use RROS on the nash, the auto-brightness satisfies me.

**Comment by xNombre** [comment]
This feature is already present in crdroid since we ship 
prebuilt Turbo.

**Comment by daiaji** [comment]
Where is the switch for this function?
