### ISSUE TITLE
how did you compile the Poco M3 kernel?

### ISSUE THREAD

**Issue by lucaszanella** [crdroidandroid/crdroid_features#62]
I see that you got Android 12 working on the Poco M3. Could you guys kindly tell me how did you compile the kernel and made it run on the Poco M3?

I'm trying to compile this kernel https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/lime-q-oss for my Poco M3

I did:

```
export ARCH=arm64 && export SUBARCH=arm64
export CROSS_COMPILE=/opt/aosp_prebuilts/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export DTC_EXT="/opt/google_misc/misc/linux-x86/dtc/dtc"
make ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- vendor/citrus-perf_defconfig
make ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- EXTRA_CFLAGS="-I $PWD/techpack/display/pll/ -I $PWD/techpack/camera/drivers/cam_sensor_module/cam_cci/  -I $PWD/techpack/camera/drivers/cam_req_mgr -DSDCARDFS_VERSION= -I $PWD/" -j$(nproc --all) 2>&1 | tee kernel.log
```
and unpacked/repacked boot.img with

```
unpackbootimg -i boot.img -o boot_img_unpacked

mkbootimg --kernel "$SCRIPT_DIR/devices/$DEVICE/kernel/k/arch/arm64/boot/Image.gz" \
    --ramdisk boot.img-ramdisk \
    --dtb boot.img-dtb \
    --cmdline "$(< boot.img-cmdline)" \
    --base "$(< boot.img-base)" \
    --kernel_offset "$(< boot.img-kernel_offset)" \
    --ramdisk_offset "$(< boot.img-ramdisk_offset)" \
    --tags_offset "$(< boot.img-tags_offset)" \
    --dtb_offset "$(< boot.img-dtb_offset)" \
    --os_version "$(< boot.img-os_version)" \
    --os_patch_level "$(< boot.img-os_patch_level)" \
    --pagesize "$(< boot.img-pagesize)" \
    --header_version "$(< boot.img-header_version)" \
    --hashtype "$(< boot.img-hashtype)" \
    --board "$(< boot.img-board)" \
    -o ../boot.img
```

but it won't boot. I get stuck on the Poco M3 screen. I tried unpacking/repacking the original boot.img with the original kernel just to see if I was repacking wrong but it worked, so my repack is working.

I think the issue might be with dtbo inside the kernel, because my compiled kernel has 28mb vs 32mb from the original one. It's worth noting that the original one is for Android 11 and the one I compiled is for Android 10 but I doubt this is the problem because both are 4.19.x and usually one kernel works over 2 Android versions.

I also tried adding `CONFIG_BUILD_ARM64_DT_OVERLAY=y` to

`vendor/citrus-perf_defconfig` but it also won't boot.

**Comment by gwolf2u** [comment]
wrong repo project?

**Comment by lattice0** [comment]
not wrong repo, I just didn't have other place to write
