### ISSUE TITLE
Pixel features into ROM

### ISSUE THREAD

**Issue by andrey6060** [crdroidandroid/crdroid_features#63]
![IMG_20220420_202940_267](https://user-images.githubusercontent.com/74371390/164288780-c943da69-6206-46d9-b7ee-2c4c7284ab8c.jpg)
Like these features. It would very good. Some other ROMs has these. Screenshot from module description.

**Comment by andrey6060** [comment]
Evolution X has these features by default. Pixel Experience too. Sorry, I can't find specific commits

**Comment by andrey6060** [comment]
This can be helpful maybe

https://github.com/PixelExperience/frameworks_base/blob/896e4776a896cf9adb2ec186d81e4368e0d4144a/core/java/com/android/internal/util/custom/PixelPropsUtils.java

**Comment by neobuddy89** [comment]
You can let us know how to enable.

**Comment by neobuddy89** [comment]
We already have PixelPropsUtils

**Comment by andrey6060** [comment]
> You can let us know how to enable.

https://github.com/Kingsman44/Pixelify this module enables these features

**Comment by andrey6060** [comment]
Implemented or postponed?

**Comment by gwolf2u** [comment]
Postponed
