### ISSUE TITLE
Option for more columns in quick settings 

### ISSUE THREAD

**Issue by haikosaw** [crdroidandroid/crdroid_features#64]
I don't know if this is the best way for a feature request. I also don't know if it's been discussed already.
But I for one would like to see this feature in crDroid, an option for more than 2 columns in QS. Xtenden ROM has this, sadly I can't give better pointers as to how to do this than that and searching Github for keywords; https://github.com/Project-Xtended/frameworks_base/commit/f73540b745c7eb8b6c4c4b7560669106a0b0d8fa

**Comment by gwolf2u** [comment]
not quite yet possible with current code we have on crDroid 8
