### ISSUE TITLE
Backup and Restore crDroid Settings

### ISSUE THREAD

**Issue by nucspl** [crdroidandroid/crdroid_features#65]
Unless it's already a thing and I'm just blind as a bat.

With so many settings, having a backup would be nice to have for those off-chances that something breaks; it'd be quite a hassle to go through all the settings again after a re-flash. It would also be neat when switching from one device to another. Backups just generally give peace of mind.

**Comment by gwolf2u** [comment]
not possible due to changes we are doing between crDroid revisions
some features may get dropped and when importing on top, can cause unexpected issues
