### ISSUE TITLE
Status bar icons are not visible

### ISSUE THREAD

**Issue by vinaykharayat** [crdroidandroid/crdroid_features#66]
How to increase this width in crDroid so that all icons or data is visible on status bar properly?
![Screenshot_20220620-093107_Settings~2.png](https://user-images.githubusercontent.com/23337757/174523626-0995ef9b-1d3e-4f4e-b9fb-484cd07d5eea.png)

**Comment by gwolf2u** [comment]
not possible via settings
can be done by device overlay
