### ISSUE TITLE
Feature request: network filesystem support in kernel

### ISSUE THREAD

**Issue by Efreak** [crdroidandroid/crdroid_features#67]
Please enable nfs and cifs network filesystems in the kernel, I'd like to be able to mount nfs, cifs shares using [Multi-Mount](https://github.com/clifforama/multi-mount).

MS-DOS/FAT filesystem would also be appreciated (I've got a 1gb microsd card I use as a flash drive. TWRP recognized it, but Android didn't until I reformatted it; I'm assuming it's a filesystem issue, but it might not be).

I've got some guesses about what kernel options need to be configured at [Efreak/android_kernel_motorola_msm8953](https://github.com/Efreak/android_kernel_motorola_msm8953/compare/crdroidandroid:android_kernel_motorola_msm8953:11.0...11.0) (doing this with minimal changes was *annoying*. menuconfig reorders and enables things on saving *even if I haven't toggled anything*, I had to commit that just to revert it)

**Comment by gwolf2u** [comment]
this is device specific request so better ask device maintainer in forum or if available device specific telegram
