### ISSUE TITLE
[feature request]: allow disabling screenshot sound

### ISSUE THREAD

**Issue by soredake** [crdroidandroid/crdroid_features#68]
Example commits from spark os:
https://github.com/Spark-Rom/frameworks_base/commit/b12faaab3f0057b152d15e659ace5d1d0839ba7b
https://github.com/Spark-Rom/packages_apps_Settings/commit/77a143ecf1693aef4a9c3aa64b613fbdfc8a8fef

**Comment by gwolf2u** [comment]
WIP in https://github.com/crdroidandroid/android_frameworks_base/pull/868
