### ISSUE TITLE
[Feature Request] Add a13 display resolution changer

### ISSUE THREAD

**Issue by proganime1200** [crdroidandroid/crdroid_features#77]
Like on newer pixel devices they can change diplau resolution like 720 1080 might be good if this added ive seen it uses global.settings to modify the screen resolution

**Comment by proganime1200** [comment]
![images](https://user-images.githubusercontent.com/32473502/206258508-711a7905-efd2-4511-a68d-c6e69069454e.jpeg)
Just like this but with 720 added

**Comment by gwolf2u** [comment]
this is device specific and not really our focus to push on all devices
if concerned about battery life, really not much benefit
more benefit can come out of 60/120 Hz (or similar) toggle
