### ISSUE TITLE
[Feature Request] Bring back game dashboard by google or make it optional to enable

### ISSUE THREAD

**Issue by proganime1200** [crdroidandroid/crdroid_features#78]
![images (1) (1)](https://user-images.githubusercontent.com/32473502/206260608-911ae17a-56e7-4f4b-9108-9a97c95846ac.jpeg)
Just like this as we can stream our games to youtube or maybe just add atleast the youtube stream feature

**Comment by gwolf2u** [comment]
we have out own game panel / dashboard
google one is proprietary
