### ISSUE TITLE
[Feature request] Bring back smart charging to 9.0

### ISSUE THREAD

**Issue by Lippiece** [crdroidandroid/crdroid_features#82]
Hi. Thank you for your work. Apologies if this is the wrong repo to post this. 

I've updated from 8.9 to 9.0 and found that Smart Charging feature is missing. Am I to understand that since it's in the Readme to the repo, it's a planned feature and will be included later?

**Comment by gwolf2u** [comment]
smart charging is there
just ask maintainer to add support for it
