### ISSUE TITLE
So brighter lock screen wallpaper 

### ISSUE THREAD

**Issue by vgcvbcvncncncn** [crdroidandroid/crdroid_features#87]
a lock screen  was too bright
![IMG_20230407_220231_268](https://user-images.githubusercontent.com/1568101/230663525-edfe0e2b-643b-4c61-a4bb-adfbc8272c8b.jpg)
![IMG_20230407_220230_866](https://user-images.githubusercontent.com/1568101/230663542-08300ecc-3a75-4ff6-b098-327fad4d1e32.jpg)
![IMG_20230407_220231_268](https://user-images.githubusercontent.com/1568101/230663565-28ebde2a-e850-4878-b18f-3cdecf0bf0b3.jpg)

But after touching to enter the pin code and return it becomes normal for once
![IMG_20230407_220231_268](https://user-images.githubusercontent.com/1568101/230663579-c651a88a-3a08-48f8-8c2d-e288f9ea2276.jpg)
![IMG_20230407_220230_866](https://user-images.githubusercontent.com/1568101/230663583-2893e9e3-65b9-4d0c-b942-e5110c44ce6a.jpg)

**Comment by gwolf2u** [comment]
Use issue_tracker
