### ISSUE TITLE
Battery limit option missing

### ISSUE THREAD

**Issue by stull-e** [crdroidandroid/crdroid_features#96]
Hi there,
first of all: thank you for your work. You're doing a great job!

After a long time without updating my phone (shame on me) I reinstalled the latest version of crDroid on it. With the new ROM (9.8 / Android 13 / build 2023-08-15) i am missing the battery limit option (stop tripper level / start trigger level) on my phone. On your github page it says that its still a feature but neither me nor the settings search can find it. Should be under: settings > cdDroid Settings > Misc?! I am attaching an image of the Misc-Settings page (in german - sorry).

Setup:
POCO X3 NFC (surya)
crDroidAndroid-13.0-20230815-surya-v9.8 (build 2023-08-15)
NikGapps-qiraht-arm64-13-20230904
not rooted

Sidenote:
Since I wanted to try out LineageOS I installed and still run with the LineageOS bootloder. First impression is, that everything runs smoothly.

Thanks for your help!
Stull-e

![Screenshot_20230905-134627_Einstellungen](https://github.com/crdroidandroid/crdroid_features/assets/123722733/411278ad-9d7a-46eb-a8e0-d76e0049e2ea)

**Comment by gwolf2u** [comment]
battery limit option has moved under battery page
if not there, ask your device maintainer to add support for new implementation
#noissue
